name: SkyWars
version: 2.0.0
api: 1.14.0
main: SkygridRex\skywars\SkyWarsPlugIn
author: SkygridRex, TheKillerTacos
description: SkygridRex SkyWars mini-game
commands:
 skw:
  description: "SkyWars mini-game"
  permission: mc.plugin.skywars
permissions:
 ftk.plugin.skywars:
  description: "mc.plugin.skywars"
  default: op
#Ill be fixing Permissions, since seem to be badly configured! - TheKillerTacos
